// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tilefgbbjhxnlclwnotp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpbGVmZ2Jiamh4bmxjbHdub3RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzOTI2MDksImV4cCI6MjA4Mzk2ODYwOX0.g9gOeL4kLTwohOGYIsjC6HECJzcurTkkMCsfc3LzT10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});